### ISSUE TITLE
Implement 'Copy' for Access Token

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#43]
I disabled the text input for the token access. To make it easy for the user let's allow them to copy the access token with a button press. Also make sure to have a growl notification that they copied the token.

![https://i.imgur.com/puWfzkk.png](https://i.imgur.com/puWfzkk.png)

**Comment by EmergentBehavior** [comment]
jQuery zClip is extremely outdated and doesn't really support versions of Flash above 11 (current version is 13.x). Since there isn't a newer version of zClip, I recommend we just use the latest beta branch 2.x of ZeroClipboard directly (with its associated ZeroClipboard.swf file).

I successfully implemented this feature using CoffeeScript (though I much prefer raw JavaScript), but I did not push the change since it would require us to rewrite all our zclip calls and I wanted to run that by everyone first. Here is the CS snippet:

```
#Copy Access Token on 'Copy'
accessTokenCopy = new ZeroClipboard($('#access-token-copy'))

accessTokenCopy.on 'copy', (e) ->
  clipboard = e.clipboardData
  clipboard.setData 'text/plain', $('#access-token').val()
  return

accessTokenCopy.on 'aftercopy', (e) ->
  if e.success['text/plain']
    $.growl
      title: 'Done!'
      icon: 'glyphicon glyphicon-ok'
      message: 'Successfully copied your access token.'
    ,
      template:
        icon_type: 'class'
        container: '<div class="col-xs-10 col-sm-10 col-md-3 alert alert-success"></div>'

      position:
        from: 'bottom'
        align: 'right'

  else
    $.growl
      title: 'Whoops!'
      icon: 'glyphicon glyphicon-remove'
      message: 'Failed to copy your access token.'
    ,
      template:
        icon_type: 'class'
        container: '<div class="col-xs-10 col-sm-10 col-md-3 alert alert-danger"></div>'

      position:
        from: 'bottom'
        align: 'right'

  return
```

In index.html, ZeroClipboard.js (2.x) would need to be loaded and the `a` tag for copy would need the id `access-token-copy`.

**Comment by EmergentBehavior** [comment]
Whoops. Didn't mean to close. Reopened.

**Comment by super3** [comment]
Seems like a decent justification. Go ahead and implement it.

**Comment by EmergentBehavior** [comment]
My last commit resolves this issue, but I should note that the copy code is a bit verbose, so when the codebase stabilizes a bit later we can clean it up into a reusable function.
