### ISSUE TITLE
Fix Search Functionality 

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#46]
We implemented a hash+key for the downloads, but we didn't update the search bar. 
![https://i.imgur.com/j9T1ufp.png](https://i.imgur.com/j9T1ufp.png)

**Comment by EmergentBehavior** [comment]
What's the expected behavior here? Is it that either a growl comes back displaying the error message in the returned JSON or straight away downloading the associated file?

**Comment by super3** [comment]
Well when the search bar was first implemented we didn't have a decryption key, just a hash for a lookup. Now a link looks something like this:

http://node2.storj.io/api/download/d1ec85d142ef9d47ed0274fb7b0eaf3487e41cb081db76a359485a7ba0d27b4c?key=3ba16b077e6799dcbef76bc62f08c41d8fde59fc596df614dd0daf62ad9a939e

Containing the hash first, and then the decryption key next.  So we need a process so that users can download files from other nodes by searching for the hash, and then providing a decryption key.

This could perhaps be done with a single really long export code. Which is just the end part of the url portion `d1ec85d142ef9d47ed0274fb7b0eaf3487e41cb081db76a359485a7ba0d27b4c?key=3ba16b077e6799dcbef76bc62f08c41d8fde59fc596df614dd0daf62ad9a939e`. The user would just copy paste this into the search bar to download the file from another node. Alternate functionality is that is just gets added to their upload files list. 

### Some Steps:

1) We add an export button to the UI.
![image](https://i.imgur.com/ScotfWa.png)
2) Export button copies the file hash, and decryption key to the clipboard.
3) Paste in the export string to the search bar and the item will get added to the uploaded files list
![image2](https://i.imgur.com/lkGSeGf.png)
4) Growl notification on success or failure.

**Comment by EmergentBehavior** [comment]
Steps 1&2 in commit 9eb4774934fa (though no export button, just copying hash+key from click hash).

**Comment by EmergentBehavior** [comment]
Here's the path I will take for the rest:
- ~~After user pastes material, regex form validation ensures that the search query takes the form `[hash]?key=[key]` with alphanumeric characters (besides the `?key=` part).~~
- ~~If validation fails, growl indicates failure due to formatting.~~
- ~~If validated, clear query from search bar and post to API.~~
- ~~If API returns error (e.g. 'insufficient balance'), growl accordingly.~~
- ~~If API returns success, growl accordingly and add file to uploaded file history using elements of makeHandler(), etc.~~
