### ISSUE TITLE
Fix Free Token Loop

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#53]
If you create a new access token, you can 1GB of free space. You can endlessly create new tokens and get free space. 

Need some sort of rate limiting to keep people from exploiting this.

**Comment by EmergentBehavior** [comment]
I think this is worth thinking about a bit more. Is this an edge case? I know during testing it's easy to do this but I imagine that most people aren't going to create and keep track of 100 access tokens because it will be hard to remember which files are stored on each one. 

I think you can create multiple Dropbox accounts to (each with free 2 GB) but I don't think most people do that in practice (without good reason).

People could also create multiple Twitter accounts to game that system too.

One concern I have is anonymity: keeping identity records on each node (e.g. where limited amount of tokens can be tied to IP or e-mail address or something) could help, but I don't know if we really want to do that.

**Comment by super3** [comment]
Well access tokens are not tied to the actual file storage. From my experience, once people find out about this someone will exploit it to bleed a bunch bandwidth from a node. 

Yes people could create multiple Dropbox accounts, but it doesn't really have a core effect on Dropbox service while it could affect service on a small node. Twitter account gaming is not that bad. At least we get a bunch of tweets about Storj out there. 

I agree anonymity is important. I suggest we use IP addresses, and keep them for a few days before scrubbing them from the system. If users want connection anonymity they are going to have to go through a proxy, Tor, or some sort of Storj bounce system.
